#!/usr/bin/env python3
"""
Simple Backend HTTP Server for Testing F-Stack Proxy
Listens on 127.0.0.1:8080
"""

import http.server
import socketserver
import sys

PORT = 8080
HOST = "127.0.0.1"

class BackendHTTPRequestHandler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        """Handle GET requests"""
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Server", "Backend-Python-Server")
        self.end_headers()
        
        response = f"""<!DOCTYPE html>
<html>
<head>
    <title>Backend Server Response</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
            background-color: #f0f0f0;
        }}
        .container {{
            background-color: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #2c3e50;
        }}
        .info {{
            background-color: #e8f4f8;
            padding: 15px;
            border-left: 4px solid #3498db;
            margin: 20px 0;
        }}
        code {{
            background-color: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: monospace;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>✓ Backend Server Response</h1>
        <p>This response was generated by the <strong>backend HTTP server</strong> running on <code>127.0.0.1:{PORT}</code></p>
        
        <div class="info">
            <h3>Request Information:</h3>
            <ul>
                <li><strong>Path:</strong> <code>{self.path}</code></li>
                <li><strong>Method:</strong> <code>{self.command}</code></li>
                <li><strong>Client:</strong> <code>{self.client_address[0]}:{self.client_address[1]}</code></li>
            </ul>
        </div>
        
        <p>If you're seeing this page, it means:</p>
        <ol>
            <li>F-Stack proxy received your request from the network</li>
            <li>The proxy successfully forwarded it to this backend server</li>
            <li>This backend server generated this response</li>
            <li>The proxy is now forwarding this response back to you</li>
        </ol>
        
        <p style="color: #27ae60; font-weight: bold;">🎉 The HTTP reverse proxy is working correctly!</p>
    </div>
</body>
</html>"""
        
        self.wfile.write(response.encode('utf-8'))
    
    def do_POST(self):
        """Handle POST requests"""
        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length).decode('utf-8') if content_length > 0 else ""
        
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Server", "Backend-Python-Server")
        self.end_headers()
        
        response = f"""<!DOCTYPE html>
<html>
<head>
    <title>Backend Server POST Response</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 50px auto;
            padding: 20px;
        }}
        .data {{
            background-color: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }}
    </style>
</head>
<body>
    <h1>POST Request Received</h1>
    <p><strong>Path:</strong> {self.path}</p>
    <p><strong>Data Length:</strong> {content_length} bytes</p>
    <div class="data">
        <h3>Posted Data:</h3>
        <pre>{post_data if post_data else "(empty)"}</pre>
    </div>
</body>
</html>"""
        
        self.wfile.write(response.encode('utf-8'))
    
    def log_message(self, format, *args):
        """Custom log format"""
        sys.stdout.write("[Backend Server] %s - %s\n" % (self.address_string(), format % args))

if __name__ == "__main__":
    with socketserver.TCPServer((HOST, PORT), BackendHTTPRequestHandler) as httpd:
        print(f"Backend HTTP Server running on http://{HOST}:{PORT}")
        print(f"This server will handle requests forwarded from the F-Stack proxy")
        print(f"Press Ctrl+C to stop")
        print("-" * 60)
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down backend server...")
            sys.exit(0)
